### PR TITLE
Unpin gVisor version

### PR DESCRIPTION
**Pull request by marcinwyszynski**
## Type of change

- [x] New feature (non-breaking change that adds functionality);

### Development

- [x] All necessary variables have been defined, with defaults if applicable;
- [x] The HCL code is formatted;
- [ ] An AMI has been created in some AWS account, and the AMI is working as expected;

### Code review

- [x] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached;
- [x] This pull request is no longer marked as "draft";
- [x] Reviewers have been assigned;
- [ ] Changes have been reviewed by at least one other engineer;

### CODE REVIEW

**Review by b4k3r — APPROVED** [review]

**Review by TheMacies — APPROVED** [review]

**Review by adamconnelly — APPROVED** [review]

**Review by cube2222 — APPROVED** [review]

**Comment by peterdeme** [comment]
@marcinwyszynski should we merge this?

**Comment by marcinwyszynski** [comment]
Honestly IDK, please take ownership of this.

**Comment by peterdeme** [comment]
@adamconnelly do you remember this history of this? I think it was unpinned, then we pinned it, then this one unpins it again.

I assume there was a version that broke something and we were frightened it happens again, but we unpin here again?

**Comment by adamconnelly** [comment]
@peterdeme it should be fine to unpin it. We originally pinned it because we thought that it had caused an issue we were seeing with our public workers, but it actually turned out to be caused by a Kernel update rather than a problem with gVisor.

**Pull request merged**
